### ISSUE TITLE
macos: creating a key fails

### ISSUE THREAD

**Issue by aaomidi** [facebookincubator/sks#5]
```go
	key := sks.FromLabelTag("label:key")

	signer, err := sks.NewKey(key.Label(), key.Tag(), true, false, nil)
	if err != nil {
		panic(err)
	}
```

```
panic: sks: error while generating key pair with label "label" and tag "key": CFError -34018

goroutine 1 [running]:
main.main()
        /Users/amir/Projects/aaomidi/tpm-ssh-agent/main.go:16 +0x244

```

**Comment by n-canter** [comment]
Hey @aaomidi,
-34018 error is a missing entitlement error. To use Secure Enclave on mac your app should be signed with a specific entitlement. More information can be found [here](https://developer.apple.com/forums/thread/728150).

I'll update our Readme to mention this.

**Comment by aaomidi** [comment]
Oops thank you so much for that, sorry that the bug report ended up being a support request D:
